# Turn on logging, and set ZMK logging to debug output
#CONFIG_ZMK_USB_LOGGING=y

# ---------------------------------------------------------
# Power Management
# ---------------------------------------------------------

# Standard Sleep (Bluetooth stays on, fast wake-up)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Deep Sleep / Soft Off (Bluetooth off, saves maximum power)
CONFIG_ZMK_PM_SOFT_OFF=y

# ---------------------------------------------------------
# ZMK Studio
# ---------------------------------------------------------
