name: ZMK Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  changes:
    runs-on: ubuntu-latest
    outputs:
      totem: ${{ steps.filter.outputs.totem }}
      corneish_zen: ${{ steps.filter.outputs.corneish_zen }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            totem:
              - 'totem/**'
              - 'shared/**'
              - 'build-totem.yaml'
            corneish_zen:
              - 'corneish_zen/**'
              - 'shared/**'
              - 'build-corneish_zen.yaml'

  build-totem:
    needs: [vars, changes]
    if: needs.changes.outputs.totem == 'true' || github.event_name == 'workflow_dispatch'
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: "build-totem.yaml"
      config_path: "totem"
      archive_name: "firmware_totem_${{ needs.vars.outputs.sha_short }}"

  build-corneish_zen:
    needs: [vars, changes]
    if: needs.changes.outputs.corneish_zen == 'true' || github.event_name == 'workflow_dispatch'
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: "build-corneish_zen.yaml"
      config_path: "corneish_zen"
      archive_name: "firmware_corneish_zen_${{ needs.vars.outputs.sha_short }}"

  # THIS IS THE JOB FOR BRANCH PROTECTION
  ci-gatekeeper:
    needs: [build-totem, build-corneish_zen]
    if: always() # Always run, even if previous jobs were skipped
    runs-on: ubuntu-latest
    steps:
      - name: Check build results
        run: |
          # Fails if any dependent job failed or was cancelled
          if [[ "${{ needs.build-totem.result }}" == "failure" || "${{ needs.build-totem.result }}" == "cancelled" || \
                "${{ needs.build-corneish_zen.result }}" == "failure" || "${{ needs.build-corneish_zen.result }}" == "cancelled" ]]; then
            echo "One or more builds failed or were cancelled."
            exit 1
          fi
          echo "All builds either passed or were correctly skipped."
