name: Totem Build

on:
  push:
    paths:
      - 'totem/**'
      - 'shared/**'
      - 'build-totem.yaml'
      - '.github/workflows/totem.yml'
  pull_request:
    paths:
      - 'totem/**'
      - 'shared/**'
      - 'build-totem.yaml'
      - '.github/workflows/totem.yml'
  workflow_dispatch:

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  build:
    needs: vars
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: "build-totem.yaml"
      config_path: "totem"
      archive_name: "totem_firmware_${{ needs.vars.outputs.sha_short }}"
